import { Inter } from "@next/font/google";
import Head from "next/head";
import About from "./about";
import Contact from "./contact";
import HomePage from "./home";
import Portfolio from "./portfolio";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sazal Islam || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
        <About />
        <Portfolio />
        <Contact />
      </main>
    </>
  );
}
